export const arrayItems = [
  {
    name: "Pesgunta e resposta",
    id: "q&a",
    description: "Responda a perguntas com base no conhecimento existente",
    option: {
      model: "text-davinci-003",
      temperature: 0,
      max_tokens: 100,
      top_p: 1,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "Correção de Gramática",
    id: "grammerCorrection",
    description: "Corrige frases para o inglês padrão.",
    option: {
      model: "text-davinci-003",
      temperature: 0,
      max_tokens: 100,
      top_p: 1,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "Resumir para um aluno da 2ª série",
    id: "summary",
    description: "Traduz texto difícil em conceitos mais simples.",
    option: {
      model: "text-davinci-003",
      temperature: 0.7,
      max_tokens: 64,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "inglês para outros idiomas",
    id: "translate",
    description: "Traduz texto em inglês para francês, espanhol e portguês.",
    option: {
      model: "text-davinci-003",
      temperature: 0.3,
      max_tokens: 100,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "Filme para Emoji",
    id: "movieToEmoji",
    description: "Converta títulos de filmes em emoji.",
    option: {
      model: "text-davinci-003",
      temperature: 0,
      max_tokens: 100,
      top_p: 1,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "Explique o código",
    id: "explainCode",
    description: "Explique um pedaço complicado de código.",
    option: {
      model: "code-davinci-002",
      temperature: 0,
      max_tokens: 64,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "JavaScript para Python",
    id: "jstopy",
    description: "Converta expressões JavaScript simples em Python.",
    option: {
      model: "code-davinci-002",
      temperature: 0,
      max_tokens: 64,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
];
